### ISSUE TITLE
In stackblitz, "Error: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"

### ISSUE THREAD

**Issue by raj2033** [stackblitz/core#669]
After installation of required packages, while importing, i get the following error:
> Error: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

Here is my **[polymer app](https://stackblitz.com/edit/polymer-3-music-app?file=my-element.js)**. According to the **[solution here](https://github.com/Polymer/polymer-starter-kit/issues/1123#issuecomment-402239658), i need to delete the node_modules** and try reinstalling. But in stackblitz i cannot access node_modules or terminal. 

Please provide a valid solution to make the imports work. then only i can proceed with building the app.

**Comment by tiliev** [comment]
@raj2033, the application appears to be working. Do you still experience this behavior or we can close this issue?

**Comment by flatmax** [comment]
I am not confident that this problem is resolved yet with polymer 3 and npm.
We have a method for resolving these issues, it is to do with removing nested @polymer modules. Check it out here :
https://github.com/Polymer/polymer/issues/5407

**Comment by Ghostfly** [comment]
+1, using lit-element, impossible to correctly get it working..

**Comment by guzmanpaniagua** [comment]
Here you have a working example 
[lit-element with typescript](https://stackblitz.com/edit/typescript-litelement-example?file=Cat.ts)

it is like a fork off
[initialize-property-values-when-using-typescript-decorators](https://lit-element.polymer-project.org/guide/properties#initialize-property-values-when-using-typescript-decorators)

from the documentation 
[lit-element guide](https://lit-element.polymer-project.org/guide)

but to make it work I have to:

1) change the import in index.ts from 
`import './my-element.js';`
to
`import './my-element.js';`
I think this is needed because the way typescript is compiled the js file did not exist yet 

2) remove the definition
`customElements.define('my-element', MyElement);`
I think it is needed because the `@customElement('my-element')` already  do that

3) I also added a tsconfig.json file with 
`{
  "compilerOptions": {
    "target": "es6",
    "module": "es6"
  }
}`
because a strange error with es5 classes and polymer way of registering
`Error: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

Hope it helps somebody still looking for a solution

**Comment by Gwalks91** [comment]
I had this issue pop up as well, this might be a really naive solution, but couldn't we just do a check before trying to register? 
From dom-module.js: 
`if(!customElements.get('dom-module')) {
  customElements.define('dom-module', DomModule);
}`

We do not want to try and register twice. This does not solve the root cause, however it does fix the issue.

Now like I said before, this is a naive solution because I am not sure of all the working parts. Please let me know if I am going about trying to fix this is the wrong way.
